config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations', sessions: 'users/sessions' }
  root 'sightings#index'
  resources :interest_locations
  resources :sightings
  

end

app/models/sighting.rb
class Sighting < ActiveRecord::Base
	belongs_to :user

	# ALERT_MESSAGE = "Meter Maid is handing out TICKETS near by".freeze

	# def notify
	# 	@interest_locations = InterestLocation.all
	# 	@interest_locations.each do |interest_location|
	# 		dist = find_distance([self.latitude, self.longitude], [interest_location.latitude, interest_location.longitude])
	# if interest_location.radius && interest_location.radius > dist
	# 			# send_message(interest_location.user.try(:phone_number), ALERT_MESSAGE)
	# 			send_message("+17049955069", ALERT_MESSAGE)
	# 		end
	# 	end
	# end

	def self.get_cordinates(arr)
		arr.map do |element|
			[element.latitude, element.longitude]
		end
	end

	def to_radians(degree)
		degree * Math::PI / 180
	end

	def find_distance(last_post, user_settings)
		r = 6373
		dlon = to_radians(user_settings[1] - last_post[1])
		dlat = to_radians(user_settings[0] - last_post[0])
		a = (Math.sin(dlat/2) * Math.sin(dlat/2)) + (Math.cos(to_radians(last_post[0])) * Math.cos(to_radians(user_settings[0])) * (Math.sin(dlon/2) * Math.sin(dlon/2)))
		c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a))
		d = r * c
	end

	def format_phone_number(arg)
		"+1" + arg.gsub(/[() -]/,"")
	end

	def send_email(array)
		puts "*********************************"
		array.each do |x|
			person = User.find(x)
			puts "Send an email to #{person.email}"
		end
		puts "USERS IS: #{array}"
		puts "*********************************"
	end
	# private
	# def send_message(phone_number, alert_message)
	# 	account_sid = ENV['TWILIO_ACCOUNT_SID']
	# 	auth_token = ENV['TWILIO_AUTH_TOKEN']

	# 	# set up a client to talk to the Twilio REST API
	# 	@client = Twilio::REST::Client.new account_sid, auth_token

	# 	@twilio_number = ENV['TWILIO_NUMBER']
	# 	@client.account.messages.create({
	# 		:from => @twilio_number,
	# 		:to => phone_number,
	# 		:body => alert_message
	# 	});
	# end

	def alert_users(all_instances)
		user_ids = target_users([self.latitude, self.longitude], all_instances)
		send_sms(user_ids)
	end

	private

	def target_users(array1, all_instances)
		users = []
		all_instances.each do |instance|
			distance = find_distance(array1, [instance.latitude, instance.longitude])
			# 0.402 km equals 1/4 mile. 
			# This will be the radius for now.
			# the circle on interest_locations map reflects that as it is set to 402
			if distance < (0.402)
				users.push(instance.user_id)
			end
		end
		users.uniq
	end


	def send_sms(array)
		account_sid = ENV['TWILIO_API_KEY_SID']
		auth_token = ENV['TWILIO_AUTH_TOKEN']
		client = Twilio::REST::Client.new account_sid, auth_token

		from = "+13057056922"

		array.each do |user_id|
			recepient = User.find(user_id)
			if recepient.phone.length == 10
				client.account.messages.create({
					:from => from,
					:to => format_phone_number(recepient.phone),
					:body => "Hello from ParkNark. Ticket maid has been spotted near you. Happy Parking!"
					})
				puts "Sent message to #{recepient.email}"
			end
		end
	end

end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
  before_action :set_sighting, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /sightings
  # GET /sightings.json
  def index
    @sightings = Sighting.where('created_at >= ?', (Time.now - 28800))
    gon.array_of_cor = Sighting.get_cordinates(@sightings)
    # @gon = gon.array_of_cor
  end

  # GET /sightings/1
  # GET /sightings/1.json
  def show
    redirect_to sightings_path
  end

  # GET /sightings/new
  def new
    @sighting = current_user.sightings.build
  end

  # GET /sightings/1/edit
  def edit
  end

  # POST /sightings
  # POST /sightings.json
  def create
    # @alert_message = "Meter Maid is around."
    @sighting = current_user.sightings.build(sighting_params)
    # @sighting.notify
    respond_to do |format|

      # send_message("+17049955069", @alert_message)

      if @sighting.save

        format.html { redirect_to @sighting, notice: 'Sighting was successfully created.' }
        format.json { render :show, status: :created, location: @sighting }

        ################################################################
        @sighting.alert_users(InterestLocation.all)
        
        # users = @sighting.target_users(post_array, locations)
        # @sighting.send_email(users)
        ################################################################
      else
        format.html { render :new }
        format.json { render json: @sighting.errors, status: :unprocessable_entity }
      end
    end


  end

  # PATCH/PUT /sightings/1
  # PATCH/PUT /sightings/1.json
  def update
    respond_to do |format|
      if @sighting.update(sighting_params)
        format.html { redirect_to @sighting, notice: 'Sighting was successfully updated.' }
        format.json { render :show, status: :ok, location: @sighting }
      else
        format.html { render :edit }
        format.json { render json: @sighting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sightings/1
  # DELETE /sightings/1.json
  def destroy
    @sighting.destroy
    respond_to do |format|
      format.html { redirect_to sightings_url, notice: 'Sighting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sighting
      @sighting = Sighting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sighting_params
      params.require(:sighting).permit(:day, :latitude, :longitude)
    end

    # def send_message(phone_number, alert_message)
    #   account_sid = ENV['TWILIO_ACCOUNT_SID']
    #   auth_token = ENV['TWILIO_AUTH_TOKEN']

    #   # set up a client to talk to the Twilio REST API
    #   @client = Twilio::REST::Client.new account_sid, auth_token

    #   @twilio_number = ENV['TWILIO_NUMBER']
    #   @client.account.messages.create({
    #   	:from => @twilio_number,
    #   	:to => phone_number,
    #   	:body => alert_message
    #   });
    # end

end

app/helpers/sightings_helper.rb
module SightingsHelper
end

app/views/sightings/_form.html.erb
<%= form_for(@sighting) do |f| %>
  <% if @sighting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sighting.errors.count, "error") %> prohibited this sighting from being saved:</h2>

      <ul>
      <% @sighting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="wrapper">
<!--     <div class="field">
      <%#= f.label :day %><br>
      <%#= f.text_field :day %>
    </div> -->
    <div class="field">
      <div class="label">
        <%#= f.label :latitude %>
        <p>LATITUDE</p>
      </div>
      <div class="input">
        <%= f.text_field :latitude, :id => "lat", :readonly => true , placeholder: "Populating..."%>
      </div>
    </div>

    <div class="field">
      <div class="label">
        <%#= f.label :longitude%>
        <p>LONGITUDE</p>
      </div>
      <div class="input">
        <%= f.text_field :longitude, :id => "long", :readonly => true, placeholder: "...Please Wait"  %>
      </div>
    </div>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/sightings/edit.html.erb
<h1>Editing Sighting</h1>

<%= render 'form' %>

<%= link_to 'Show', @sighting %> |
<%= link_to 'Back', sightings_path %>

app/views/sightings/index.html.erb
<%= include_gon %>
<img class="fix" src=" /assets/ParkNarkCenter.png "alt="Smiley face"  height="81px" width="82%" onmouseover="this.src=' /assets/ParkNarkRight.gif '" onmouseout="this.src=' /assets/ParkNarkCenter.png '"class="img-responsive center-block">
<input value="markers" type="hidden" id="page_id" /> 
<div class="container">
  <div class="top-tab">
    <p>LAST 8 HOURS AROUND YOU</p>
  </div>
  <div id="map"></div>
</div>

<div class="sightings-bottom">

  <div class="sightings-b-l">
    <div class="link">
      <p><%= link_to 'SEND ALERT', new_sighting_path %></p>
    </div>
<!--     <div class="footer">
      <p>TO SEND ALERTS</p>
    </div> -->
  </div>


  <div class="sightings-b-r">
    <div class="link">
      <p><%= link_to 'ALERT ME', interest_locations_path %></p>
    </div>
<!--     <div class="footer">
      <p>TO RECEIVE ALERTS</p>
    </div> -->
  </div>

</div>


<!-- <div>
  <h1>Once the appropriate map is created DELETE ME! (I AM A DIV)</h1>
  <#% @sightings.each do |sighting| %>
    <p><b>Day:</b> <%#= sighting.day %></p>
    <p><b>Latitude: </b> <%#= sighting.latitude %></p>
    <p><b>Longitude: </b> <%#= sighting.longitude %></p>
    <td><%#= link_to 'Show', sighting %></td>
    <td><%#= link_to 'Edit', edit_sighting_path(sighting) %></td>
    <%#= link_to 'Destroy', sighting, method: :delete, data: { confirm: 'Are you sure?' } %>
  <%# end %>
</div> -->

app/views/sightings/new.html.erb
<img class="fix" src=" /assets/ParkNarkCenter.png "alt="Smiley face"  height="81px" width="82%" onmouseover="this.src=' /assets/ParkNarkRight.gif '" onmouseout="this.src=' /assets/ParkNarkCenter.png '"class="img-responsive center-block">
<%# if notice || alert %>
<!-- <div class="disappear">
	<p id="notice"><%#= notice %></p>
	<p class="alert"><%#= alert %></p>
</div> -->
<%# end %>

<div class="form-n">
	<%= render 'form' %>
</div>

<div class="back-n">
	<%= link_to 'Back', sightings_path %>
</div>

app/views/sightings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Day:</strong>
  <%= @sighting.day %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @sighting.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @sighting.longitude %>
</p>

<%= link_to 'Edit', edit_sighting_path(@sighting) %> |
<%= link_to 'Back', sightings_path %>