config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations', sessions: 'users/sessions' }
  root 'sightings#index'
  resources :interest_locations
  resources :sightings
  

end

app/models/interest_location.rb
class InterestLocation < ActiveRecord::Base
	belongs_to :user

	def self.get_cordinates(arr)

		arr.map do |element|
			[element.latitude, element.longitude]
		end

	end
end

app/controllers/interest_locations_controller.rb
class InterestLocationsController < ApplicationController
  before_action :set_interest_location, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /interest_locations
  # GET /interest_locations.json
  def index
    @interest_locations = current_user.interest_locations
    gon.array_of_cor = InterestLocation.get_cordinates(@interest_locations)
    gon.poop = false
  end

  # GET /interest_locations/1
  # GET /interest_locations/1.json
  def show
    redirect_to interest_locations_path
  end

  # GET /interest_locations/new
  def new
    @interest_location = current_user.interest_locations.build
  end

  # GET /interest_locations/1/edit
  def edit
  end

  # POST /interest_locations
  # POST /interest_locations.json
  def create
    @interest_location = current_user.interest_locations.build(interest_location_params)
    @interest_location.radius = 2
    respond_to do |format|
      if @interest_location.save
        format.html { redirect_to @interest_location, notice: 'Interest location was successfully created.' }
        format.json { render :show, status: :created, location: @interest_location }
      else
        format.html { render :new }
        format.json { render json: @interest_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interest_locations/1
  # PATCH/PUT /interest_locations/1.json
  def update
    respond_to do |format|
      if @interest_location.update(interest_location_params)
        format.html { redirect_to @interest_location, notice: 'Interest location was successfully updated.' }
        format.json { render :show, status: :ok, location: @interest_location }
      else
        format.html { render :edit }
        format.json { render json: @interest_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interest_locations/1
  # DELETE /interest_locations/1.json
  def destroy
    @interest_location.destroy
    respond_to do |format|
      format.html { redirect_to interest_locations_url, notice: 'Interest location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interest_location
      @interest_location = InterestLocation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interest_location_params
      params.require(:interest_location).permit(:latitude, :longitude, :radius)
    end
end

app/helpers/interest_locations_helper.rb
module InterestLocationsHelper
end

app/views/interest_locations/_form.html.erb
<%= form_for(@interest_location) do |f| %>
  <% if @interest_location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interest_location.errors.count, "error") %> prohibited this interest_location from being saved:</h2>

      <ul>
      <% @interest_location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="wrapper">
    <div class="field">
      <div class="label">
      <%#= f.label :latitude %>
        <p>LATITUDE</p>
      </div>
      <div class="input">
        <%= f.text_field :latitude, :id => "lat", :readonly => true , placeholder: "Populating..." %>
      </div>
    </div>

    <div class="field">
      <div class="label">
      <%#= f.label :longitude %>
        <p>LONGITUDE</p>
      </div>
      <div class="input">
        <%= f.text_field :longitude, :id => "long", :readonly => true, placeholder: "...Please Wait" %>
      </div>  
    </div>
  </div>
<!--   <div class="field">
    <%#= f.label :radius %><br>
    <%#= f.number_field :radius %>
  </div> -->
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/interest_locations/edit.html.erb
<h1>Editing Interest Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @interest_location %> |
<%= link_to 'Back', interest_locations_path %>

app/views/interest_locations/index.html.erb
<%= include_gon %>         
<img class="fix" src=" /assets/ParkNarkCenter.png "alt="Smiley face"  height="81px" width="82%" onmouseover="this.src=' /assets/ParkNarkRight.gif '" onmouseout="this.src=' /assets/ParkNarkCenter.png '"class="img-responsive center-block">
<div class="container-il">
	<div class="top-tab">
		<p>YOUR CURRENT SCOPE</p>
	</div>
	<div id="map"></div>
</div>

<% if @interest_locations.length == 0 %>
	<div class="empty">
		<p>Click Add To Start</p>
		<p>Receiving Notifications</p>
	</div>
<% else %>
	<div class="scroll">
		<div class="space"></div>
		<% @interest_locations.each do |item| %>
		<div class="box">
			<div class="item">
				<p><%= item.created_at.strftime("%a %b %d %-I:%M  %p") %></p>
			</div>
			<div class="remove">
				<p><%= link_to 'X', item, method: :delete, data: { confirm: 'Are you sure?' }  %></p>
			</div>
		</div>
		<div class="space"></div>
		<% end %>
	</div>
<% end %>
<div class="link-to-profile">
	<%= link_to "HOME", sightings_path %>
</div>
<div class="add-il">
	<%= link_to 'ADD', new_interest_location_path %>
</div>

app/views/interest_locations/new.html.erb
<img class="fix" src=" /assets/ParkNarkCenter.png "alt="Smiley face"  height="81px" width="82%" onmouseover="this.src=' /assets/ParkNarkRight.gif '" onmouseout="this.src=' /assets/ParkNarkCenter.png '"class="img-responsive center-block">

<div class="form-iln">
	<%= render 'form' %>
</div>

<div class="bottom-iln">
	<p><%= link_to 'Back', interest_locations_path %></p>
	<p><%= link_to 'Profile', sightings_path %></p>
</div>

app/views/interest_locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @interest_location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @interest_location.longitude %>
</p>

<p>
  <strong>Radius:</strong>
  <%= @interest_location.radius %>
</p>

<%= link_to 'Edit', edit_interest_location_path(@interest_location) %> |
<%= link_to 'Back', interest_locations_path %>